### ISSUE TITLE
TypeError: this.content.trim is not a function  

### ISSUE THREAD

**Issue by joelstein** [ckeditor/vite-plugin-ckeditor5#7]
I followed [these instructions](https://ckeditor.com/docs/ckeditor5/latest/installation/frameworks/react.html#vite) for building CKEditor from source with Vite 4.3.3 and React 18.2.0, but I'm getting the following console error:

```
ckeditor.tsx:157 TypeError: this.content.trim is not a function
    at IconView._updateXMLContent (iconview.js:65:73)
    at IconView.render (iconview.js:48:14)
    at IconView.<anonymous> (observablemixin.js:181:45)
    at IconView.fire (emittermixin.js:146:47)
    at <computed> [as render] (observablemixin.js:184:29)
    at ViewCollection._renderViewIntoCollectionParent (viewcollection.js:179:18)
    at ViewCollection.<anonymous> (viewcollection.js:63:18)
    at ViewCollection.fire (emittermixin.js:146:47)
    at ViewCollection.addMany (collection.js:106:18)
    at ViewCollection.add (collection.js:75:21) {phase: 'initialization', willEditorRestart: false}
```

Here is my component:

```js
import { CKEditor } from "@ckeditor/ckeditor5-react";
import { ClassicEditor } from "@ckeditor/ckeditor5-editor-classic";
import { Essentials } from "@ckeditor/ckeditor5-essentials";
import { Paragraph } from "@ckeditor/ckeditor5-paragraph";
import { Bold, Italic } from "@ckeditor/ckeditor5-basic-styles";

const editorConfiguration = {
    plugins: [Essentials, Bold, Italic, Paragraph],
    toolbar: ["bold", "italic"],
};

export default function Editor() {
    return (
        <CKEditor
            editor={ClassicEditor}
            config={editorConfiguration}
            data="<p>Hello from CKEditor 5!</p>"
        />
    );
}
```

**Comment by joelstein** [comment]
Aha! It was caused by [vite-plugin-svgr](https://github.com/pd4d10/vite-plugin-svgr) trying to convert the SVGs.

I resolved it with the following in vite.config.js:

```js
export default defineConfig({
    plugins: [
        react(),
        ckeditor5({ theme: require.resolve("@ckeditor/ckeditor5-theme-lark") }),
        svgr({
            exportAsDefault: true,
            exclude: "**/@ckeditor/**",
        }),
    ],
});
```

**Comment by Witoso** [comment]
Thanks for the issue, and the fix! 😄
